from numpy import array, ndarray, sum as np_sum

from common.angular_velocity import omega_from_v_r
from omni_wheel import OmniWheel


class OmnidirectionalRobot:
    def __init__(self, num_wheels, velocity_color='orange', wheel_color='black', motor_velocities=None):
        if num_wheels < 3:
            raise ValueError("Omnidirectional robot must have at least 3 wheels")
        self.num_wheels = num_wheels
        self.wheels: list[OmniWheel] = []
        self.velocity_color = velocity_color
        self.wheel_color = wheel_color
        self.position = array([0, 0])
        self.orientation = 0

        self.motor_velocities = array([0] * num_wheels) if motor_velocities is None else motor_velocities

        if len(self.motor_velocities) != num_wheels:
            raise ValueError("Motor velocities must be provided for each wheel")

    def move(self, x, y, orientation):
        self.position = array([x, y])
        self.orientation = orientation
        for wheel in self.wheels:
            wheel.orientation += orientation
            wheel.distance_from_robot_frame = (
                wheel.distance_from_robot_frame[0] + x, wheel.distance_from_robot_frame[1] + y)

    def add_wheel(self, wheel: OmniWheel):
        if len(self.wheels) < self.num_wheels:
            self.wheels.append(wheel)
        else:
            raise ValueError("All wheels have been added")

    def plot(self, ax):
        ax.set_aspect('equal')
        for wheel in self.wheels:
            wheel.plot(ax, color=self.wheel_color)

    def plot_velocity(self, ax):
        ax.set_aspect('equal')
        for wheel, vel in zip(self.wheels, self.motor_velocities):
            wheel.velocity = vel
            wheel.plot(ax, color=self.wheel_color)
            wheel.plot_velocity(ax, color=self.velocity_color)

    def get_angular_velocity(self):
        # 1. First calculate each wheel's velocity
        # 2. Calculate the angular velocity generated by the wheel velocities. You know that each wheel linear velocity
        # is the cross product of the wheel distance from the robot frame and the angular velocity of the robot.
        # since we already calculated the wheel velocities, we can use them to calculate the angular velocity.
        # 3. Calculate the robot angular velocity by summing each wheel's angular velocity.
        angular_velocities = [omega_from_v_r(wheel.get_velocity_components(motor_velocity),
                                             wheel.distance_from_robot_frame)
                              for wheel, motor_velocity
                              in zip(self.wheels, self.motor_velocities)]
        return sum(angular_velocities)

    def get_linear_velocity(self) -> ndarray:
        linear_velocity = np_sum([wheel.get_velocity_components(motor_velocity) for wheel, motor_velocity in
                                  zip(self.wheels, self.motor_velocities)], axis=0)
        return linear_velocity
